# We use the "Secure Development Tools" which needs to be installed in any DevOps organization that use 
# this YAML file. The free public Azure Pipelines for OSS includes these tools by default already.

# TODO: add ESLint once it's added to the "Secure Development Tools". TSLint is depricated.

variables:
- name: ubuntu_image
  value: ubuntu-20.04
- name: mac_image
  value: macOS-13
- name: windows_image
  value: windows-2022

jobs:
- job: bld_native
  strategy:
    matrix:
      Linux_release_64:
        image.name: ${{ variables.ubuntu_image }}
        asm: "-asm"
        bld: "-release_64"
      Linux_debug_64:
        image.name: ${{ variables.ubuntu_image }}
        asm: ""
        bld: "-debug_64"
      Linux_release_32:
        image.name: ${{ variables.ubuntu_image }}
        asm: ""
        bld: "-release_32"
      Linux_debug_32:
        image.name: ${{ variables.ubuntu_image }}
        asm: ""
        bld: "-debug_32"
      Mac_release_64:
        image.name: ${{ variables.mac_image }}
        asm: "-asm"
        bld: "-release_64"
      Mac_debug_64:
        image.name: ${{ variables.mac_image }}
        asm: ""
        bld: "-debug_64"
      Mac_release_arm:
        image.name: ${{ variables.mac_image }}
        asm: ""
        bld: "-release_arm"
      Mac_debug_arm:
        image.name: ${{ variables.mac_image }}
        asm: ""
        bld: "-debug_arm"
      Windows_release_64:
        image.name: ${{ variables.windows_image }}
        asm: ""
        bld: "-release_64"
      Windows_debug_64:
        image.name: ${{ variables.windows_image }}
        asm: ""
        bld: "-debug_64"
      Windows_release_32:
        image.name: ${{ variables.windows_image }}
        asm: ""
        bld: "-release_32"
      Windows_debug_32:
        image.name: ${{ variables.windows_image }}
        asm: ""
        bld: "-debug_32"
    maxParallel: 12
  pool:
    vmImage: $(image.name)
  steps:
  - task: PythonScript@0
    inputs:
      scriptSource: inline
      script: from urllib.request import urlretrieve; urlretrieve('https://developer.download.nvidia.com/compute/cuda/11.2.2/network_installers/cuda_11.2.2_win10_network.exe', 'cuda_11.2.2_win10_network.exe')
    condition: startsWith(variables['image.name'], 'windows')
    displayName: CUDA download installer
  # CUDA installation https://docs.nvidia.com/cuda/pdf/CUDA_Installation_Guide_Windows.pdf
  # the list of NVIDIA CUDA install options is at: https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html
  - script: |
      SET PATH=%PATH%;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\
      SET CudaToolkitDir=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
      cuda_11.2.2_win10_network.exe -s nvcc_11.2 visual_studio_integration_11.2 cudart_11.2
      IF ERRORLEVEL 1 (
        ECHO cuda_11.2.2_win10_network.exe FAILED
        EXIT /B 201
      )
      .\build.bat $(bld) $(asm)
    condition: startsWith(variables['image.name'], 'windows')
    displayName: win bld_native
  - script: |
      sudo apt --yes update
      if [ $? -ne 0 ]; then 
         exit 107
      fi
      sudo apt --yes install nvidia-cuda-toolkit
      if [ $? -ne 0 ]; then 
         exit 93
      fi
      /bin/sh ./build.sh $(bld) $(asm)
    condition: startsWith(variables['image.name'], 'ubuntu')
    displayName: linux bld_native
  - script: |
      /bin/sh ./build.sh $(bld) $(asm)
    condition: startsWith(variables['image.name'], 'macOS')
    displayName: mac bld_native
  - publish: bld/lib
    artifact: libebm-$(image.name)$(bld)
    displayName: Publish native shared library
  - publish: bld/asm/
    artifact: asm-$(image.name)
    condition: ne(length(variables['asm']), 0)
    displayName: Publish assembly x64

- job: bld_vis
  pool:
    vmImage: ${{ variables.ubuntu_image }}
  steps:
  - script: |
      cd shared/vis
      npm install
      npm run build-prod
    displayName: bld_vis
  - publish: shared/vis/dist
    artifact: vis
    displayName: Publish interpret-inline.js library

- job: bld_npm_package
  pool:
    vmImage: ${{ variables.ubuntu_image }}
  steps:
  - script: |
      cd shared/vis
      npm install
      npm run build-prod
      npm pack
      mkdir pkg
      cp *.tgz pkg/
    displayName: bld_npm_package
  - publish: shared/vis/pkg
    artifact: npm
    displayName: Publish npm package

- job: bld_R_package
  pool:
    vmImage: ${{ variables.ubuntu_image }}
  steps:
  - script: | 
      cd R
      sudo apt --yes update
      if [ $? -ne 0 ]; then
        exit 201
      fi
      sudo apt --yes install texlive-latex-base texlive-fonts-extra
      if [ $? -ne 0 ]; then
        exit 201
      fi
      Rscript build.R
    displayName: Rscript build.R
  - script: cat bld/tmp/R/interpret.Rcheck/00install.out
    condition: failed()
    displayName: Display errors
  - publish: bld/R
    artifact: R
    displayName: Publish R package

- job: bld_sdist_package
  pool:
    vmImage: ${{ variables.ubuntu_image }}
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.8
  - script: |
      python -m pip install --upgrade pip setuptools wheel
      cd python/interpret-core
      python setup.py sdist -d ../../bld/sdist
      cd ../interpret
      python setup.py sdist -d ../../bld/sdist
    displayName: interpret bld_sdist_package
  - publish: bld/sdist
    artifact: sdist
    displayName: Publish sdist python package

- job: docs
  dependsOn: bld_sdist_package
  pool:
    vmImage: ${{ variables.ubuntu_image }}
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.8
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: sdist
      itemPattern: sdist/interpret-core-*.tar.gz
      path: $(System.ArtifactsDirectory)/sdist
    displayName: Download sdist
  - script: |
      cd $(System.ArtifactsDirectory)/sdist
      tarball_path=$(echo interpret-core-*.tar.gz)
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install "$tarball_path"[debug,notebook,plotly,lime,sensitivity,shap,linear,treeinterpreter,dash,skoperules,testing]
      cd $(Build.SourcesDirectory)/docs/
      pip install -r requirements.txt
      /bin/sh ./build.sh
    displayName: Build docs
  - publish: docs/interpret_docs/_build/html/
    artifact: docs
    displayName: Publish docs

- job: bld_bdist_package
  dependsOn: [bld_native, bld_vis]
  pool:
    vmImage: ${{ variables.ubuntu_image }}
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.8
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: libebm-$(windows_image)-release_64
      itemPattern: |
        *.dll
        *.pdb
      path: python/interpret-core/interpret/root/bld/lib
    displayName: Copy win release_64 library to bld/lib directory
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: libebm-$(windows_image)-debug_64
      itemPattern: |
        *.dll
        *.pdb
      path: python/interpret-core/interpret/root/bld/lib
    displayName: Copy win debug_64 library to bld/lib directory
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: libebm-$(ubuntu_image)-release_64
      path: python/interpret-core/interpret/root/bld/lib
    displayName: Copy linux-release-64 shared library to bld/lib directory
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: libebm-$(ubuntu_image)-debug_64
      path: python/interpret-core/interpret/root/bld/lib
    displayName: Copy linux-debug-64 shared library to bld/lib directory
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: libebm-$(mac_image)-release_64
      path: python/interpret-core/interpret/root/bld/lib
    displayName: Copy mac-release-64 shared library to bld/lib directory
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: libebm-$(mac_image)-debug_64
      path: python/interpret-core/interpret/root/bld/lib
    displayName: Copy mac-debug-64 shared library to bld/lib directory
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: libebm-$(mac_image)-release_arm
      path: python/interpret-core/interpret/root/bld/lib
    displayName: Copy mac-release-arm shared library to bld/lib directory
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: libebm-$(mac_image)-debug_arm
      path: python/interpret-core/interpret/root/bld/lib
    displayName: Copy mac-debug-arm shared library to bld/lib directory
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: vis
      path: python/interpret-core/interpret/root/bld/lib
    displayName: Copy interpret-inline.js to python lib directory
  - script: |
      python -m pip install --upgrade pip setuptools wheel
      cd python/interpret-core
      python setup.py bdist_wheel -d ../../bld/bdist
      cd ../interpret
      python setup.py bdist_wheel -d ../../bld/bdist
    displayName: interpret bld_bdist_package
  - publish: bld/bdist
    artifact: bdist
    displayName: Publish bdist python package

- job: test_native
  dependsOn: bld_native
  strategy:
    matrix:
      Linux_release_64:
        image.name: ${{ variables.ubuntu_image }}
        bld: "-release_64"
        extra: ""
      Linux_debug_64:
        image.name: ${{ variables.ubuntu_image }}
        bld: "-debug_64"
        extra: ""
      Linux_release_32:
        image.name: ${{ variables.ubuntu_image }}
        bld: "-release_32"
        extra: ""
      Linux_debug_32:
        image.name: ${{ variables.ubuntu_image }}
        bld: "-debug_32"
        extra: ""
      Mac_release_64:
        image.name: ${{ variables.mac_image }}
        bld: "-release_64"
        extra: ""
      Mac_debug_64:
        image.name: ${{ variables.mac_image }}
        bld: "-debug_64"
        extra: ""
      Windows_release_64:
        image.name: ${{ variables.windows_image }}
        bld: "-release_64"
        extra: "-analysis"
      Windows_debug_64:
        image.name: ${{ variables.windows_image }}
        bld: "-debug_64"
        extra: ""
      Windows_release_32:
        image.name: ${{ variables.windows_image }}
        bld: "-release_32"
        extra: "-analysis"
      Windows_debug_32:
        image.name: ${{ variables.windows_image }}
        bld: "-debug_32"
        extra: ""
    maxParallel: 10
  pool:
    vmImage: $(image.name)
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: libebm-$(image.name)$(bld)
      path: bld/lib
    displayName: Copy native library to bld/lib directory
  - task: PythonScript@0
    inputs:
      scriptSource: inline
      script: from urllib.request import urlretrieve; urlretrieve('https://developer.download.nvidia.com/compute/cuda/11.2.2/network_installers/cuda_11.2.2_win10_network.exe', 'cuda_11.2.2_win10_network.exe')
    condition: startsWith(variables['image.name'], 'windows')
    displayName: Download CUDA installer
  - script: |
      /bin/sh ./shared/libebm/tests/libebm_test.sh $(bld) -existing_debug_64 -existing_release_64 -existing_debug_arm -existing_release_arm -asan
    condition: startsWith(variables['image.name'], 'macOS')
    displayName: mac test_native
  - script: |
      /bin/sh ./shared/libebm/tests/libebm_test.sh $(bld) -existing_debug_64 -existing_release_64 -existing_debug_32 -existing_release_32
    condition: and(startsWith(variables['image.name'], 'ubuntu'), ne(variables['Build.Reason'], 'Schedule'))
    displayName: linux test_native (CI)
  - script: |
      /bin/sh ./shared/libebm/tests/libebm_test.sh $(bld) -existing_debug_64 -existing_release_64 -existing_debug_32 -existing_release_32 -valgrind
    condition: and(startsWith(variables['image.name'], 'ubuntu'), eq(variables['Build.Reason'], 'Schedule'))
    displayName: linux test_native (Schedule)
  - script: |
      SET PATH=%PATH%;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\
      SET CudaToolkitDir=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
      cuda_11.2.2_win10_network.exe -s nvcc_11.2 visual_studio_integration_11.2 cudart_11.2
      IF ERRORLEVEL 1 (
        ECHO cuda_11.2.2_win10_network.exe FAILED
        EXIT /B 201
      )
      .\shared\libebm\tests\libebm_test.bat $(bld) -existing_debug_64 -existing_release_64 -existing_debug_32 -existing_release_32
    condition: and(startsWith(variables['image.name'], 'windows'), ne(variables['Build.Reason'], 'Schedule'))
    displayName: win test_native (CI)
  - script: |
      SET PATH=%PATH%;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\
      SET CudaToolkitDir=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
      cuda_11.2.2_win10_network.exe -s nvcc_11.2 visual_studio_integration_11.2 cudart_11.2
      IF ERRORLEVEL 1 (
        ECHO cuda_11.2.2_win10_network.exe FAILED
        EXIT /B 201
      )
      .\shared\libebm\tests\libebm_test.bat $(bld) -existing_debug_64 -existing_release_64 -existing_debug_32 -existing_release_32 $(extra)
    condition: and(startsWith(variables['image.name'], 'windows'), eq(variables['Build.Reason'], 'Schedule'))
    displayName: win test_native (Schedule)

- job: test
  dependsOn: bld_bdist_package
  strategy:
    matrix:
      Linux38Python:
        python.version: 3.8
        image.name: ${{ variables.ubuntu_image }}
      Linux39Python:
        python.version: 3.9
        image.name: ${{ variables.ubuntu_image }}
      Linux310Python:
        python.version: 3.10
        image.name: ${{ variables.ubuntu_image }}
      Win38Python:
        python.version: 3.8
        image.name: ${{ variables.windows_image }}
      Win39Python:
        python.version: 3.9
        image.name: ${{ variables.windows_image }}
      Win310Python:
        python.version: 3.10
        image.name: ${{ variables.windows_image }}
      Mac38Python:
        python.version: 3.8
        image.name: ${{ variables.mac_image }}
      Mac39Python:
        python.version: 3.9
        image.name: ${{ variables.mac_image }}
      Mac310Python:
        python.version: 3.10
        image.name: ${{ variables.mac_image }}
    maxParallel: 9
  pool:
    vmImage: $(image.name)
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(python.version)
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: bdist
      itemPattern: interpret_core-*.whl
      targetPath: $(System.ArtifactsDirectory)/bdist
  # we copy the tests to a new location to test the installed package rather than the source files
  - script: |
      python -m pip install --upgrade pip setuptools wheel
      FOR %%A IN ($(System.ArtifactsDirectory)\bdist\interpret_core-*.whl) DO SET "install_file=%%A"
      python -m pip install "%install_file%"[debug,notebook,plotly,lime,sensitivity,shap,linear,treeinterpreter,dash,skoperules,testing]
      set PATH=%PATH%;%GeckoWebDriver%
      mkdir "$(Agent.TempDirectory)\zqmr"
      mkdir "$(Agent.TempDirectory)\zqmr\t"
      xcopy /E "$(Build.SourcesDirectory)\python\interpret-core\tests\*" "$(Agent.TempDirectory)\zqmr\t\"
      cd /D "$(Agent.TempDirectory)\zqmr\t"
      python -m pytest -vv -n auto --junitxml=junit/test-results.xml --cov=interpret --cov-report=xml --cov-report=html
    condition: startsWith(variables['image.name'], 'windows')
    displayName: pytest (win)
  # we copy the tests to a new location to test the installed package rather than the source files
  - script: |
      python -m pip install --upgrade pip setuptools wheel
      cd $(System.ArtifactsDirectory)/bdist
      install_file=$(echo interpret_core-*.whl)
      python -m pip install "$install_file"[debug,notebook,plotly,lime,sensitivity,shap,linear,treeinterpreter,dash,skoperules,testing]
      mkdir -p "$(Agent.TempDirectory)/zqmr/t"
      cp -r "$(Build.SourcesDirectory)/python/interpret-core/tests/" "$(Agent.TempDirectory)/zqmr/t/"
      cd "$(Agent.TempDirectory)/zqmr/t"
      python -m pytest -vv -n auto --junitxml=junit/test-results.xml --cov=interpret --cov-report=xml --cov-report=html
    condition: not(startsWith(variables['image.name'], 'windows'))
    displayName: pytest (non-win)
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: $(Agent.TempDirectory)/zqmr/t/junit/test-results.xml
      testRunTitle: Publish test results for Python $(python.version) at $(image.name)
    condition: succeededOrFailed()
    displayName: Publish test results
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(Agent.TempDirectory)/zqmr/t/coverage.xml
      # reportDirectory: $(Agent.TempDirectory)/zqmr/t/**/htmlcov
    condition: startsWith(variables['image.name'], 'windows')
    displayName: Publish test coverage results

- job: publish_source_code
  dependsOn: [test_native, test]
  pool:
    vmImage: ${{ variables.ubuntu_image }}
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.8
  - script: |
      cd python/interpret-core
      python -m pip install --upgrade black
      black --check .
    displayName: black formatting check
  - publish: $(System.ArtifactsDirectory)
    artifact: source_code

schedules:
- cron: "0 12 * * *"
  branches:
    include:
    - develop
  always: true
  displayName: Daily midnight build
